version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - NO_CACHE=1
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    volumes:
      - ./src:/var/www/html
    command: >
      /bin/sh -c "
      mkdir -p /var/www/html/storage/logs /var/www/html/bootstrap/cache
      && chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
      && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
      && php artisan optimize
      && php-fpm -y /usr/local/etc/php-fpm.conf -R"
    networks:
      - app_network

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app_network

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - app_network

networks:
  app_network:
    external:
      name: your_network_name
