version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - NO_CACHE=${NO_CACHE}  # Add a build argument to control cache
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./src:/var/www/html
    command: >
      /bin/sh -c "
      mkdir -p /var/www/html/storage/logs 
      && chown -R laravel:laravel /var/www/html/storage 
      && chmod -R 775 /var/www/html/storage 
      && php artisan optimize
      && php-fpm -y /usr/local/etc/php-fpm.conf -R"

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

networks:
  default:
    external:
      name: your_network_name
