version: '3.8'

services:
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/bin/sh", "-c", "composer install --optimize-autoloader"]
    networks:
      - app_network

  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile
      args:
        - NO_CACHE=1
    volumes:
      - ./src:/var/www/html
    env_file:
      - ./src/.env.production
    depends_on:
      - composer
    command: >
      /bin/sh -c "
      mkdir -p /var/www/html/storage/logs 
      && chown -R laravel:laravel /var/www/html/storage /var/www/html/bootstrap/cache
      && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
      && php artisan optimize
      && php-fpm -y /usr/local/etc/php-fpm.conf -R"
    networks:
      - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    external:
      name: your_network_name
