version: 2.1

executors:
  docker-executor:
    docker:
      - image: php:8-fpm-alpine
    working_directory: ~/repo

jobs:
  deploy:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7

      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:1r+0RI8mIHtGT9P+b/LWVjSJufWbk/mh+dFb2M/uRWQ"

      - run:
          name: Install System Dependencies
          command: |
            set -ex
            apk update
            apk add --no-cache \
              docker-compose \
              openssh

      - run:
          name: Ensure target directory exists and has correct permissions
          command: |
            ssh -o "StrictHostKeyChecking=no" ubuntu@${SSH_HOST} '
              sudo mkdir -p ~/repo &&
              sudo chown -R $(whoami):$(whoami) ~/repo &&
              chmod -R 755 ~/repo'

      - run:
          name: Deploy Application
          command: |
            set -ex
            cd ~/repo
            scp -r -o "StrictHostKeyChecking=no" src ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload src directory"; exit 1; }
            scp -o "StrictHostKeyChecking=no" src/.env.production ubuntu@${SSH_HOST}:~/repo/src/.env || { echo "Failed to upload .env file"; exit 1; }
            scp -o "StrictHostKeyChecking=no" docker-compose.prod.yaml ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload docker-compose.prod.yaml"; exit 1; }
            scp -o "StrictHostKeyChecking=no" php.prod.dockerfile ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload php.prod.dockerfile"; exit 1; }
            scp -o "StrictHostKeyChecking=no" nginx.dockerfile ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload nginx.dockerfile"; exit 1; }
            scp -o "StrictHostKeyChecking=no" composer.dockerfile ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload composer.dockerfile"; exit 1; }
            scp -r -o "StrictHostKeyChecking=no" nginx ubuntu@${SSH_HOST}:~/repo/ || { echo "Failed to upload nginx directory"; exit 1; }
            ssh -o "StrictHostKeyChecking=no" ubuntu@${SSH_HOST} '
              set -ex
              cd ~/repo &&
              if ! docker network ls | grep -q your_network_name; then
                docker network create your_network_name;
              fi && 
              docker-compose -f docker-compose.prod.yaml pull &&
              docker-compose -f docker-compose.prod.yaml up -d &&
              docker-compose -f docker-compose.prod.yaml exec -T php php artisan migrate --force ||
              { echo "Migration failed"; exit 1; } &&
              docker-compose -f docker-compose.prod.yaml exec -T php php artisan config:cache ||
              { echo "Config cache failed"; exit 1; } &&
              docker-compose -f docker-compose.prod.yaml exec -T php php artisan route:cache ||
              { echo "Route cache failed"; exit 1; } &&
              docker-compose -f docker-compose.prod.yaml exec -T php php artisan view:cache ||
              { echo "View cache failed"; exit 1; }'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy